DROP TABLE BD_2.COUNTRY CASCADE CONSTRAINTS;
DROP TABLE BD_2.CITY CASCADE CONSTRAINTS;
DROP TABLE BD_2.POSTAL_CODE CASCADE CONSTRAINTS;
DROP TABLE BD_2.ADDRESS CASCADE CONSTRAINTS;
DROP TABLE BD_2.PERSON CASCADE CONSTRAINTS;
DROP TABLE BD_2.PHONE;
DROP TABLE BD_2.ROLE_T CASCADE CONSTRAINTS;
DROP TABLE BD_2.ROLES_T;
DROP TABLE BD_2.COLOR CASCADE CONSTRAINTS;
DROP TABLE BD_2.PRODUCER CASCADE CONSTRAINTS;
DROP TABLE BD_2.PRODUCT_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE BD_2.ABSTRACT_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE BD_2.PRODUCT_SPECIMEN CASCADE CONSTRAINTS;
DROP TABLE BD_2.TRANSACTION_T CASCADE CONSTRAINTS;
DROP TABLE BD_2.ORDERED_PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE BD_2.PROMOTION CASCADE CONSTRAINTS;


INSERT INTO BD_2.ROLE_T(NAME)
VALUES('ADMINISTRATOR');

INSERT INTO BD_2.ROLE_T(NAME)
VALUES('EMPLOYEE');

INSERT INTO BD_2.ROLE_T(NAME)
VALUES('CUSTOMER');

INSERT INTO BD_2.ROLE_T(NAME)
VALUES('NOT_LOGGED_IN');


INSERT INTO BD_2.COLOR(NAME)
VALUES('GREEN');

INSERT INTO BD_2.COLOR(NAME)
VALUES('SILVER');

INSERT INTO BD_2.COLOR(NAME)
VALUES('GOLD');

INSERT INTO BD_2.COLOR(NAME)
VALUES('BLUE');


INSERT INTO BD_2.PRODUCER(NAME)
VALUES('SAMSUNG');

INSERT INTO BD_2.PRODUCER(NAME)
VALUES('STEELSERIES');

INSERT INTO BD_2.PRODUCER(NAME)
VALUES('GENESIS');

INSERT INTO BD_2.PRODUCER(NAME)
VALUES('RAZER');

INSERT INTO BD_2.PRODUCER(NAME)
VALUES('LOGITECH');


INSERT INTO BD_2.PRODUCT_CATEGORY(NAME)
VALUES('LAPTOP');

INSERT INTO BD_2.PRODUCT_CATEGORY(NAME)
VALUES('COMPUTER');

INSERT INTO BD_2.PRODUCT_CATEGORY(NAME)
VALUES('SMARTPHONE');

INSERT INTO BD_2.PRODUCT_CATEGORY(NAME)
VALUES('HEADPHONES');

INSERT INTO BD_2.PRODUCT_CATEGORY(NAME)
VALUES('COMPUTER_MOUSE');


INSERT INTO BD_2.COUNTRY(NAME)
VALUES('POLAND');


INSERT INTO BD_2.CITY(COUNTRY_ID, NAME, STATE_V)
VALUES(1, 'WROCŁAW', 'STATE');

INSERT INTO BD_2.CITY(COUNTRY_ID, NAME, STATE_V)
VALUES(1, 'KRAKÓW', 'STATE');

INSERT INTO BD_2.CITY(COUNTRY_ID, NAME, STATE_V)
VALUES(1, 'GDAŃSK', 'STATE');

INSERT INTO BD_2.CITY(COUNTRY_ID, NAME, STATE_V)
VALUES(1, 'KATOWICE', 'STATE');

INSERT INTO BD_2.CITY(COUNTRY_ID, NAME, STATE_V)
VALUES(1, 'WARSZAWA', 'STATE');


INSERT INTO BD_2.POSTAL_CODE(code)
VALUES('00-001');

INSERT INTO BD_2.POSTAL_CODE(code)
VALUES('00-002');

INSERT INTO BD_2.POSTAL_CODE(code)
VALUES('00-003');

INSERT INTO BD_2.POSTAL_CODE(code)
VALUES('00-004');

INSERT INTO BD_2.POSTAL_CODE(code)
VALUES('00-005');


INSERT INTO BD_2.ADDRESS(CITY_ID, POSTAL_CODE_ID, STREET_NUMBER, FLAT_NUMBER, STREET_NAME)
VALUES(1, 1, '1', '2a', 'Ulica');

INSERT INTO BD_2.ADDRESS(CITY_ID, POSTAL_CODE_ID, STREET_NUMBER, FLAT_NUMBER, STREET_NAME)
VALUES(1, 1, '1', '2a', 'Ulica2');

INSERT INTO BD_2.ADDRESS(CITY_ID, POSTAL_CODE_ID, STREET_NUMBER, FLAT_NUMBER, STREET_NAME)
VALUES(1, 2, '1', '2a', 'Ulica1');

INSERT INTO BD_2.ADDRESS(CITY_ID, POSTAL_CODE_ID, STREET_NUMBER, FLAT_NUMBER, STREET_NAME)
VALUES(2, 3, '1', '2a', 'Ulica2');

INSERT INTO BD_2.ADDRESS(CITY_ID, POSTAL_CODE_ID, STREET_NUMBER, FLAT_NUMBER, STREET_NAME)
VALUES(2, 3, '1', '2a', 'Ulica3');

INSERT INTO BD_2.ADDRESS(CITY_ID, POSTAL_CODE_ID, STREET_NUMBER, FLAT_NUMBER, STREET_NAME)
VALUES(3, 4, '1', '2a', 'Ulica3');

INSERT INTO BD_2.ADDRESS(CITY_ID, POSTAL_CODE_ID, STREET_NUMBER, FLAT_NUMBER, STREET_NAME)
VALUES(3, 4, '1', '2a', 'Ulica2');

INSERT INTO BD_2.ADDRESS(CITY_ID, POSTAL_CODE_ID, STREET_NUMBER, FLAT_NUMBER, STREET_NAME)
VALUES(4, 5, '1', '2a', 'Ulica2');


INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	REGULAR_CUSTOMER, USERNAME)
VALUES(1, 'aaaa', 'aaaa', 'a@a.a', 'pass', sysdate, 0, 'aaa');

INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	REGULAR_CUSTOMER, USERNAME)
VALUES(2, 'bbb', 'bbb', 'b@b.b', 'pass1', sysdate, 0, 'aaa1');

INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	REGULAR_CUSTOMER, USERNAME)
VALUES(3, 'aaaa2', 'aaaa2', 'a2@a.a', 'pass3', sysdate, 1, 'aaa2');

INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	HIRING_DATE, EMPLOYEE_NUMBER, USERNAME)
VALUES(3, 'aaaa2', 'aaaa2', 'a23@a.a', 'pass3', sysdate, sysdate, 1, 'aaa2');

INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	HIRING_DATE, EMPLOYEE_NUMBER, USERNAME)
VALUES(3, 'aa2aa2', 'aaaa22', 'a243@a.a', 'pass23', sysdate, sysdate, 2, 'aaa3123122');

INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	HIRING_DATE, EMPLOYEE_NUMBER, USERNAME)
VALUES(3, 'aa2aa2', 'aaaa22', 'a24312313@a.a', 'pass23', sysdate, sysdate, 3, 'aaa221132');

INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	HIRING_DATE, EMPLOYEE_NUMBER, USERNAME)
VALUES(3, 'aa2aa2', 'aaaa22', 'a2411323@a.a', 'pass23', sysdate, sysdate, 4, 'aaa223123332');

INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	HIRING_DATE, EMPLOYEE_NUMBER, USERNAME)
VALUES(3, 'aa2aa2', 'aaaa22', 'a24233@a.a', 'pass23', sysdate, sysdate, 5, 'aaa313122');

INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	HIRING_DATE, EMPLOYEE_NUMBER, USERNAME)
VALUES(3, 'aa2aa2', 'aaaa22', 'a2231143@a.a', 'pass23', sysdate, sysdate, 6, 'aa23213122');

INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	HIRING_DATE, EMPLOYEE_NUMBER, USERNAME)
VALUES(3, 'aa2aa2', 'aaaa22', 'a24323@a.a', 'pass23', sysdate, sysdate, 7, 'aaa2321312');


INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	HIRING_DATE, EMPLOYEE_NUMBER, USERNAME)
VALUES(3, 'aa2aa2', 'aaaa22', 'a231343@a.a', 'pass23', sysdate, sysdate, 8, 'aaa3213122');


INSERT INTO BD_2.ROLES_T(PERSON_ID, ROLE_ID)
VALUES(1, 3);

INSERT INTO BD_2.ROLES_T(PERSON_ID, ROLE_ID)
VALUES(2, 3);

INSERT INTO BD_2.ROLES_T(PERSON_ID, ROLE_ID)
VALUES(3, 3);

INSERT INTO BD_2.ROLES_T(PERSON_ID, ROLE_ID)
VALUES(4, 2);

INSERT INTO BD_2.ROLES_T(PERSON_ID, ROLE_ID)
VALUES(4, 1);






