--No
INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	HIRING_DATE, EMPLOYEE_NUMBER, USERNAME)
VALUES(3, 'aa2aa2', 'aaaa22', 'a243@a.a', 'pass23', sysdate, sysdate, 2, 'aaa22');
--No
INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	HIRING_DATE, EMPLOYEE_NUMBER, USERNAME)
VALUES(3, 'aa2aa2', 'aaaa22', 'a243.a', 'pass23', sysdate, sysdate, 4, 'aaa22');
--Yes
INSERT INTO BD_2.PERSON(ADDRESS_ID, FIRSTNAME, SURNAME, E_MAIL, PASSWORD, CREATION_DATE,
	HIRING_DATE, EMPLOYEE_NUMBER, USERNAME)
VALUES(3, 'aa2aa2', 'aaaa22', 'a243@a.a', 'pass23', sysdate, sysdate, 5, 'aaa22');

--No
INSERT INTO BD_2.CITY(COUNTRY_ID, NAME, STATE_V)
VALUES(0, 'POZNAŃ', 'STATE');
--Yes
INSERT INTO BD_2.CITY(COUNTRY_ID, NAME, STATE_V)
VALUES(1, 'POZNAŃ', 'STATE');

--No
INSERT INTO BD_2.ROLES_T(PERSON_ID, ROLE_ID)
VALUES(1, 0);
--Yes
INSERT INTO BD_2.ROLES_T(PERSON_ID, ROLE_ID)
VALUES(1, 1);