ALTER TABLE
    BD_2.PERSON
ADD
    CONSTRAINT PERSON_ADDRESS_FK FOREIGN KEY(ADDRESS_ID) 
		REFERENCES BD_2.ADDRESS(ID);

ALTER TABLE
	BD_2.PHONE
ADD
	CONSTRAINT PHONE_PERSON_FK FOREIGN KEY(PERSON_ID) 
		REFERENCES BD_2.PERSON(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.ROLES_T
ADD
	CONSTRAINT ROLE_T_PERSON_FK FOREIGN KEY(PERSON_ID) 
		REFERENCES BD_2.PERSON(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.ROLES_T
ADD
	CONSTRAINT ROLES_T_ROLE_FK FOREIGN KEY(ROLE_ID) 
		REFERENCES BD_2.ROLE_T(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.CITY
ADD
	CONSTRAINT CITY_COUNTRY_FK FOREIGN KEY(COUNTRY_ID) 
		REFERENCES BD_2.COUNTRY(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.ADDRESS
ADD
	CONSTRAINT ADDRESS_CITY_FK FOREIGN KEY(CITY_ID) 
		REFERENCES BD_2.CITY(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.ADDRESS
ADD
	CONSTRAINT ADDRESS_POSTAL_CODE_FK FOREIGN KEY(POSTAL_CODE_ID) 
		REFERENCES BD_2.POSTAL_CODE(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.ORDERED_PRODUCTS
ADD
	CONSTRAINT ORDERED_PROD_TRANSACTION_T_FK FOREIGN KEY(TRANSACTION_ID) 
		REFERENCES BD_2.TRANSACTION_T(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.ORDERED_PRODUCTS
ADD
	CONSTRAINT ORDERED_PROD_PROD_SPECIMEN_FK FOREIGN KEY(PRODUCT_SPECIMEN_ID) 
		REFERENCES BD_2.PRODUCT_SPECIMEN(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.TRANSACTION_T
ADD
	CONSTRAINT TRANSACTION_T_ADDRESS_FK FOREIGN KEY(ADDRESS_ID) 
		REFERENCES BD_2.ADDRESS(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.TRANSACTION_T
ADD
	CONSTRAINT TRANSACTION_T_CUSTOMER_FK FOREIGN KEY(CUSTOMER_ID) 
		REFERENCES BD_2.PERSON(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.TRANSACTION_T
ADD
	CONSTRAINT TRANSACTION_T_EMPLOYEE_FK FOREIGN KEY(EMPLOYEE_ID) 
		REFERENCES BD_2.PERSON(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.ABSTRACT_PRODUCT
ADD
	CONSTRAINT ABSTRACT_PROD_PRODUCT_CAT_FK FOREIGN KEY(PRODUCT_CATEGORY_ID) 
		REFERENCES BD_2.PRODUCT_CATEGORY(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.ABSTRACT_PRODUCT
ADD
	CONSTRAINT ABSTRACT_PROD_PRODUCER_FK FOREIGN KEY(PRODUCER_ID) 
		REFERENCES BD_2.PRODUCER(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.PRODUCT_SPECIMEN
ADD
	CONSTRAINT PRODUCT_SPEC_ASBTRACT_PROD_FK FOREIGN KEY(ABSTRACT_PRODUCT_ID) 
		REFERENCES BD_2.ABSTRACT_PRODUCT(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.PRODUCT_SPECIMEN
ADD
	CONSTRAINT PRODUCT_SPECIMEN_COLOR_FK FOREIGN KEY(COLOR_ID) 
		REFERENCES BD_2.COLOR(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.PROMOTION
ADD
	CONSTRAINT PROMOTION_PRODUCT_CATEGORY_FK FOREIGN KEY(PRODUCT_CATEGORY_ID) 
		REFERENCES BD_2.PRODUCT_CATEGORY(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.PROMOTION
ADD
	CONSTRAINT PROMOTION_ABSTRACT_PRODUCT_FK FOREIGN KEY(ABSTRACT_PRODUCT_ID) 
		REFERENCES BD_2.ABSTRACT_PRODUCT(ID) ON DELETE CASCADE;

ALTER TABLE
	BD_2.PROMOTION
ADD
	CONSTRAINT PROMOTION_PRODUCT_SPECIMEN_FK FOREIGN KEY(PRODUCT_SPECIMEN_ID) 
		REFERENCES BD_2.PRODUCT_SPECIMEN(ID) ON DELETE CASCADE;








