CREATE SEQUENCE BD_2.COUNTRY_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.CITY_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.POSTAL_CODE_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.ADDRESS_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.PERSON_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.PHONE_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.ROLE_T_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.COLOR_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.PRODUCER_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.PRODUCT_CATEGORY_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.ABSTRACT_PRODUCT_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.PRODUCT_SPECIMEN_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.TRANSACTION_T_ID_SEQ
MINVALUE 1
INCREMENT BY 1;

CREATE SEQUENCE BD_2.PROMOTION_ID_SEQ
MINVALUE 1
INCREMENT BY 1;