DROP ROLE ADMINISTRATOR;
DROP ROLE EMPLOYEE;
DROP ROLE CUSTOMER;
DROP ROLE NOT_LOGGED_IN;

CREATE ROLE ADMINISTRATOR;
CREATE ROLE EMPLOYEE;
CREATE ROLE CUSTOMER;
CREATE ROLE NOT_LOGGED_IN;

GRANT ALL ON BD_2.PERSON
	TO ADMINISTRATOR;

GRANT SELECT, INSERT, UPDATE ON BD_2.PERSON
	TO EMPLOYEE, CUSTOMER;

GRANT ALL ON BD_2.ROLE_T
	TO ADMINISTRATOR;

GRANT SELECT ON BD_2.ROLE_T
	TO EMPLOYEE, CUSTOMER, NOT_LOGGED_IN;

GRANT ALL ON BD_2.ROLES_T
	TO ADMINISTRATOR;

GRANT SELECT ON BD_2.ROLES_T
	TO EMPLOYEE, CUSTOMER, NOT_LOGGED_IN;

GRANT ALL ON BD_2.COUNTRY
	TO ADMINISTRATOR;

GRANT SELECT ON BD_2.COUNTRY
	TO EMPLOYEE, CUSTOMER;

GRANT ALL ON BD_2.CITY
	TO ADMINISTRATOR;

GRANT SELECT, INSERT ON BD_2.CITY
	TO EMPLOYEE, CUSTOMER;

GRANT ALL ON BD_2.POSTAL_CODE
	TO ADMINISTRATOR;

GRANT SELECT, INSERT ON BD_2.POSTAL_CODE
	TO EMPLOYEE, CUSTOMER;

GRANT ALL ON BD_2.ADDRESS
	TO ADMINISTRATOR, EMPLOYEE, CUSTOMER;

GRANT SELECT ON BD_2.ORDERED_PRODUCTS
	TO ADMINISTRATOR, EMPLOYEE, CUSTOMER;

GRANT SELECT ON BD_2.TRANSACTION_T
	TO ADMINISTRATOR, CUSTOMER;

GRANT SELECT, INSERT, UPDATE ON BD_2.TRANSACTION_T
	TO EMPLOYEE;

GRANT SELECT ON BD_2.ABSTRACT_PRODUCT
	TO ADMINISTRATOR, CUSTOMER, NOT_LOGGED_IN;

GRANT ALL ON BD_2.ABSTRACT_PRODUCT
	TO EMPLOYEE;

GRANT SELECT ON BD_2.PRODUCT_SPECIMEN
	TO ADMINISTRATOR, CUSTOMER, NOT_LOGGED_IN;

GRANT ALL ON BD_2.PRODUCT_SPECIMEN
	TO EMPLOYEE;

GRANT SELECT ON BD_2.PRODUCER
	TO ADMINISTRATOR, CUSTOMER, NOT_LOGGED_IN;

GRANT ALL ON BD_2.PRODUCER
	TO EMPLOYEE;

GRANT SELECT ON BD_2.PRODUCT_CATEGORY
	TO ADMINISTRATOR, CUSTOMER, NOT_LOGGED_IN;

GRANT ALL ON BD_2.PRODUCT_CATEGORY
	TO EMPLOYEE;

GRANT SELECT ON BD_2.PROMOTION
	TO ADMINISTRATOR, CUSTOMER, NOT_LOGGED_IN;

GRANT ALL ON BD_2.PROMOTION
	TO EMPLOYEE;

GRANT ALL ON BD_2.COLOR
	TO ADMINISTRATOR, EMPLOYEE;

GRANT SELECT ON BD_2.COLOR
	TO CUSTOMER, NOT_LOGGED_IN;

GRANT ALL ON BD_2.PHONE
	TO ADMINISTRATOR, EMPLOYEE, CUSTOMER;


DROP USER ADMINISTRATOR_U;
DROP USER EMPLOYEE_U;
DROP USER CUSTOMER_U;
DROP USER NOT_LOGGED_IN_U;


CREATE USER ADMINISTRATOR_U IDENTIFIED BY a_pass;
GRANT ADMINISTRATOR TO ADMINISTRATOR_U;

CREATE USER EMPLOYEE_U IDENTIFIED BY e_pass;
GRANT EMPLOYEE TO EMPLOYEE_U;

CREATE USER CUSTOMER_U IDENTIFIED BY c_pass;
GRANT CUSTOMER TO CUSTOMER_U;

CREATE USER NOT_LOGGED_IN_U IDENTIFIED BY n_l_pass;
GRANT NOT_LOGGED_IN TO NOT_LOGGED_IN_U;








